---

- name: Install Apache packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: apache_packages
  environment: env
  when: ansible_os_family == "Debian"
  tags: [apache2, packages]

- name: enable Apache2 modules
  apache2_module: state=present name={{ item }}
  with_items: common_modules
  notify: restart Apache
  when: ansible_os_family == "Debian"
  tags: [apache2]

- name: ensure Apache service is up
  action: service name=apache2 state=started
  tags: [apache2]

- name: configure mpm prefork
  copy: src=mpm_prefork.conf dest=/etc/apache2/mods-available/mpm_prefork.conf owner=root group=root mode=0644
  notify: restart Apache
  when: ansible_os_family == "Debian"
  tags: [apache2]

- name: configure security settings
  copy: src=security.conf dest=/etc/apache2/conf-available/security.conf owner=root group=root mode=0644
  notify: restart Apache
  when: ansible_os_family == "Debian"
  tags: [apache2]

- name: make sure that there is no default website
  file: path={{ APACHE_SITES_ENABLED_CONFIG_PATH }}/000-default.conf state=absent
  notify:
  - reload Apache
  tags: [apache2]

- name: installing website config (.htaccess variant) {{ PROJECT_NAME }}
  template: src=site_htaccess.j2 dest={{ APACHE_SITES_AVAILABLE_CONFIG_PATH }}/{{ PROJECT_NAME }}.conf
  notify:
  - reload Apache
  when: use_htaccess == true
  tags: [apache2]

- name: installing website config (virtual host variant) {{ PROJECT_NAME }}
  #template: src=site_vhost.j2 dest={{ APACHE_SITES_AVAILABLE_CONFIG_PATH }}/{{ PROJECT_NAME }}.conf
  template: src=site_vhost_legacy.j2 dest={{ APACHE_SITES_AVAILABLE_CONFIG_PATH }}/{{ PROJECT_NAME }}.conf

  notify:
  - reload Apache
  when: use_htaccess == false
  tags: [apache2]

- name: create a symlink for website {{ PROJECT_NAME }}
  file: src={{ APACHE_SITES_AVAILABLE_CONFIG_PATH }}/{{ PROJECT_NAME }}.conf dest={{ APACHE_SITES_ENABLED_CONFIG_PATH }}/{{ PROJECT_NAME }}.conf state=link
  # also a handler named restart APACHE is present if needed
  notify:
  - reload Apache
  tags: [apache2]
